name: Periodic health check

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://stormy-beyond-29800.herokuapp.com/health
        max-attempts: 3
        retry-delay: 60s